"""
Base Strategy - Abstract base class for all trading strategies.

Defines the common interface that every strategy must implement.
"""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Optional

import pandas as pd

logger = logging.getLogger(__name__)


class SignalAction(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    symbol: str
    action: SignalAction
    strategy: str
    timestamp: datetime
    strength: float  # 0.0 to 1.0
    price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def is_buy(self) -> bool:
        return self.action == SignalAction.BUY

    @property
    def is_sell(self) -> bool:
        return self.action == SignalAction.SELL


@dataclass
class Position:
    """Represents an open position for strategy tracking."""
    symbol: str
    entry_price: float
    quantity: int
    entry_date: datetime
    strategy: str
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def unrealized_pnl_pct(self) -> float:
        """Calculate P&L % given current price (from metadata)."""
        if self.entry_price == 0:
            return 0.0
        current = self.metadata.get("current_price", self.entry_price)
        return (current - self.entry_price) / self.entry_price * 100


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    Subclasses must implement:
    - generate_signals: Scan universe and produce signals
    - should_enter: Validate entry conditions
    - should_exit: Validate exit conditions
    """

    def __init__(self, name: str, params: Optional[dict] = None) -> None:
        self._name = name
        self._params = params or {}
        self._positions: dict[str, Position] = {}

    @property
    def name(self) -> str:
        return self._name

    @abstractmethod
    def generate_signals(
        self,
        universe: dict[str, pd.DataFrame],
    ) -> list[Signal]:
        """
        Scan a universe of stocks and generate trading signals.

        Args:
            universe: Dict mapping symbol -> OHLCV DataFrame.

        Returns:
            List of Signal objects.
        """
        ...

    @abstractmethod
    def should_enter(self, signal: Signal) -> bool:
        """
        Validate whether a buy signal should be acted upon.

        Args:
            signal: The signal to validate.

        Returns:
            True if the entry should proceed.
        """
        ...

    @abstractmethod
    def should_exit(self, position: Position) -> bool:
        """
        Check if an open position should be closed.

        Args:
            position: The open position to check.

        Returns:
            True if the position should be exited.
        """
        ...

    def get_params(self) -> dict[str, Any]:
        """Get strategy parameters."""
        return dict(self._params)

    def set_params(self, params: dict[str, Any]) -> None:
        """Update strategy parameters."""
        self._params.update(params)

    def add_position(self, position: Position) -> None:
        """Track an opened position."""
        self._positions[position.symbol] = position

    def remove_position(self, symbol: str) -> Optional[Position]:
        """Remove and return a closed position."""
        return self._positions.pop(symbol, None)

    def get_positions(self) -> dict[str, Position]:
        """Get all open positions for this strategy."""
        return dict(self._positions)

    def has_position(self, symbol: str) -> bool:
        """Check if strategy has an open position in a symbol."""
        return symbol in self._positions

    # ── Technical Indicators (shared utilities) ──────────────────────────

    @staticmethod
    def sma(series: pd.Series, period: int) -> pd.Series:
        """Simple Moving Average."""
        return series.rolling(window=period).mean()

    @staticmethod
    def ema(series: pd.Series, period: int) -> pd.Series:
        """Exponential Moving Average."""
        return series.ewm(span=period, adjust=False).mean()

    @staticmethod
    def rsi(series: pd.Series, period: int = 14) -> pd.Series:
        """Relative Strength Index."""
        delta = series.diff()
        gain = delta.where(delta > 0, 0.0)
        loss = (-delta).where(delta < 0, 0.0)
        avg_gain = gain.ewm(com=period - 1, min_periods=period).mean()
        avg_loss = loss.ewm(com=period - 1, min_periods=period).mean()
        rs = avg_gain / avg_loss
        return (100 - (100 / (1 + rs))).fillna(50.0)

    @staticmethod
    def bollinger_bands(
        series: pd.Series,
        period: int = 20,
        std_dev: float = 2.0,
    ) -> tuple[pd.Series, pd.Series, pd.Series]:
        """Bollinger Bands. Returns (upper, middle, lower)."""
        middle = series.rolling(window=period).mean()
        std = series.rolling(window=period).std()
        upper = middle + std_dev * std
        lower = middle - std_dev * std
        return upper, middle, lower

    @staticmethod
    def adx(
        high: pd.Series,
        low: pd.Series,
        close: pd.Series,
        period: int = 14,
    ) -> pd.Series:
        """Average Directional Index (ADX)."""
        plus_dm = high.diff()
        minus_dm = -low.diff()

        plus_dm = plus_dm.where((plus_dm > minus_dm) & (plus_dm > 0), 0.0)
        minus_dm = minus_dm.where((minus_dm > plus_dm) & (minus_dm > 0), 0.0)

        tr1 = high - low
        tr2 = (high - close.shift()).abs()
        tr3 = (low - close.shift()).abs()
        tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)

        atr = tr.ewm(alpha=1 / period, min_periods=period).mean()
        atr_safe = atr.replace(0, float('nan'))
        plus_di = 100 * (plus_dm.ewm(alpha=1 / period, min_periods=period).mean() / atr_safe)
        plus_di = plus_di.fillna(0)
        minus_di = 100 * (minus_dm.ewm(alpha=1 / period, min_periods=period).mean() / atr_safe)
        minus_di = minus_di.fillna(0)

        di_sum = plus_di + minus_di
        dx = 100 * (plus_di - minus_di).abs() / di_sum.replace(0, float('nan'))
        dx = dx.fillna(0)
        adx_val = dx.ewm(alpha=1 / period, min_periods=period).mean()
        return adx_val

    @staticmethod
    def atr(
        high: pd.Series,
        low: pd.Series,
        close: pd.Series,
        period: int = 14,
    ) -> pd.Series:
        """Average True Range."""
        tr1 = high - low
        tr2 = (high - close.shift()).abs()
        tr3 = (low - close.shift()).abs()
        tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
        return tr.ewm(alpha=1 / period, min_periods=period).mean()

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name='{self._name}')"
