# Market Environment Scan Report
**Date:** 2026-05-02 18:27 UTC

---

## [1] Fear & Greed Index

| Date       | Value | Classification |
|------------|-------|----------------|
| 2026-05-02 | 39    | Fear           |
| 2026-05-01 | 26    | Fear           |
| 2026-04-30 | 29    | Fear           |
| 2026-04-29 | 26    | Fear           |
| 2026-04-28 | 33    | Fear           |
| 2026-04-27 | 47    | Neutral        |
| 2026-04-26 | 33    | Fear           |

**Trend:** Recovering from deep fear (26 → 39), but still in Fear territory for 6 of 7 days.
**Reading:** Market remains pessimistic. FNG improving from lows suggests potential bottom forming.

---

## [2] Major Coins 24h Performance

| Coin  | Price       | 24h Chg  | Vol(24h) | High       | Low        |
|-------|-------------|----------|----------|------------|------------|
| BTC   | $78,195.80  | +1.14%   | $9.99B   | $78,879.90 | $77,212.20 |
| ETH   | $2,302.32   | +0.87%   | $5.85B   | $2,324.64  | $2,278.00  |
| SOL   | $83.81      | -0.17%   | $0.98B   | $84.82     | $83.28     |
| DOGE  | $0.1078     | -0.16%   | $0.64B   | $0.1105    | $0.1073    |
| XRP   | $1.3861     | +0.81%   | $0.35B   | $1.3993    | $1.3730    |
| BNB   | $615.62     | -0.27%   | $0.17B   | $623.17    | $614.00    |

**Observation:** BTC and ETH leading the recovery (+1.14%, +0.87%). Lags on SOL/DOGE/BNB suggesting BTC-led bounce, not broad-based rally.

---

## [3] BTC Trend Analysis (30 Days)

| Metric              | Value                    |
|---------------------|--------------------------|
| Current Price       | $78,219.14               |
| 30d High            | $78,645.13               |
| 30d Low             | $66,891.66               |
| 30d Range           | 17.6%                    |
| 7d Change           | +0.8%                    |
| 30d Change          | +16.9%                   |
| MA7                 | $77,257.76 (above)       |
| MA30                | $74,212.00 (above)       |
| Daily Volatility    | 1.89%                    |
| Annualized Vol      | 36.1%                    |
| 14d Support         | $73,856.06               |
| 14d Resistance      | $78,645.13               |
| **Trend**           | **Strong Uptrend**       |

**Key Observations:**
- Price above both MA7 and MA30 — confirmed uptrend structure
- Near 30d high — testing resistance at $78,645
- 30d gain of +16.9% is significant; watch for consolidation
- Annualized vol at 36.1% is moderate — not extreme

---

## [4] BTC Perp Funding Rates

| Timestamp (UTC)      | Funding Rate | Mark Price    |
|----------------------|-------------|---------------|
| 04-29 08:00          | -0.0028%    | $77,007.66    |
| 04-29 16:00          | +0.0036%    | $75,880.57    |
| 04-30 00:00          | -0.0042%    | $75,749.80    |
| 04-30 08:00          | -0.0018%    | $76,130.00    |
| 04-30 16:00          | -0.0029%    | $76,429.20    |
| 05-01 00:00          | -0.0037%    | $76,305.50    |
| 05-01 08:00          | -0.0018%    | $77,101.10    |
| 05-01 16:00          | -0.0031%    | $78,424.73    |
| 05-02 00:00          | -0.0008%    | $78,192.00    |
| 05-02 08:00          | -0.0051%    | $78,181.60    |

**Average:** -0.0023% (slightly negative)

**Signal:** Shorts paying longs consistently — bearish crowding in derivatives.
This creates a potential short squeeze setup if price continues upward.

---

## [5] Market Overview

| Metric             | Value          |
|--------------------|----------------|
| BTC Dominance      | 58.5%          |
| Total Market Cap   | $2.68T         |
| Total 24h Volume   | $75.0B         |
| Active Cryptos     | 17,473         |

---

## Summary & Implications for Grid Bot

### Market Condition: Cautiously Bullish Contradiction
- **Price action:** Strong uptrend (+16.9% in 30d), near highs
- **Sentiment:** Fear (FNG 39) — market participants still scared
- **Derivatives:** Negative funding = shorts underwater, squeeze potential
- **Volume:** BTC 24h vol ~$10B, moderate

### Key Takeaways for Grid Strategy:
1. **Funding rate negative** = good for spot accumulation — perps traders are bearish
2. **FNG fear** while price is in uptrend = potential continuation — "wall of worry"
3. **$73,856-78,645 range** — current grid should capture this zone well
4. **Watch for:** Break above $78,645 (30d high) or break below MA30 ($74,212)

### Risk Factors:
- 17.6% range in 30d means high volatility — grid should be wide enough
- BTC dominance elevated (58.5%) — altcoins underperforming
- Funding deeply negative (-0.0051%) could flip if shorts capitulate
